### ISSUE TITLE
sdk 支持.net core

### ISSUE THREAD

**Issue by geffzhang** [Baidu-AIP/dotnet-sdk#3]
.net core 2.0已经发布半年时间，sdk 可以兼容.net core了吧

**Comment by hannixu** [comment]
可以用了，但是有个小缺憾，就是对多组文字识别，识别结果没有分割，如附加图，识别出来都是连在一起的一个句子，就不好处理了，如果能分割成多个words就很好了。



hanni_xu
 
发件人： geffzhang
发送时间： 2018-01-09 09:24
收件人： Baidu-AIP/dotnet-sdk
抄送： Subscribed
主题： [Baidu-AIP/dotnet-sdk] sdk 支持.net core (#3)
.net core 2.0已经发布半年时间，sdk 可以兼容.net core了吧

**Comment by geffzhang** [comment]
支持的话，使用netstandard 2.0 打个包呗， dotnet跨平台的微信公众号是我的，可以的欢迎约篇文章发我的公众号

**Comment by alex521** [comment]
什么时候能支持core 2.0

**Comment by chenxiaoyu3** [comment]
年后会开始对core 2.0的支持，我会在这里更新进展~

**Comment by chenxiaoyu3** [comment]
已支持
https://github.com/Baidu-AIP/dotnet-sdk/commit/cfe7b0b2b6c9314c14e865bc46ec0401c09d6f0c
