### ISSUE TITLE
在WinXp系统上抛出异常,Win7/10正常没有问题

### ISSUE THREAD

**Issue by SunflyNj** [Baidu-AIP/dotnet-sdk#8]
Baidu.Aip.AipException:  The  underlying  connection  was  closed:  An  unexpected  error  occurred  on  a  send.       
at  Baidu.Aip.AipServiceBase.SendRequetRaw(AipHttpRequest  aipRequest)       
at  Baidu.Aip.AipServiceBase.SendRequet(AipHttpRequest  aipRequest)      
 at  Baidu.Aip.AipServiceBase.PostAction(AipHttpRequest  aipReq) 

Maybe : ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3;

**Comment by chenxiaoyu3** [comment]
可能是.Net 版本的问题。建议从源码在你的平台编译上试试。

**Comment by xeonwell** [comment]
我也碰到一样的问题， 在winxp+win7上都有问题，修复如下
在auth.cs文件里，找到
`var webReq = (HttpWebRequest)WebRequest.Create(url);`

下面添加如下代码
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3;`

**Comment by PeterPanZH** [comment]
PR is welcome~
