### ISSUE TITLE
目前dll没考虑需要通过代理服务器才能上网的情况

### ISSUE THREAD

**Issue by fdstar** [Baidu-AIP/dotnet-sdk#9]
源代码中未发现设置proxy的地方，也未发现允许进行设置的Action，建议在AipServiceBase添加个可设置HttpWebRequest的virtual方法，或者Action<HttpWebRequest>属性

**Comment by chenxiaoyu3** [comment]
可以通过设置GlobalProxy 来选择代理服务器。
通过代理之后还需要设置ssl安全相关策略。

**Comment by fdstar** [comment]
请问GlobalProxy是打算实现的方案吗？我搜索了C#的源代码，没找到proxy
